apiVersion: v1
kind: Service
metadata:
  name: postgres
  labels:
    app: postgres
spec:
  ports:
  - port: 3306
  selector:
    app: postgres
  clusterIP: None
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres
spec:
  selector:
    matchLabels:
      app: postgres
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: postgres
    spec:
      containers:
      - image: postgres:latest
        name: postgres
        env:
          # Use secret in real usage
        - name: POSTGRES_ROOT_PASSWORD
          value: "123456"
        - name: POSTGRES_DATABASE
          value: wikijs
        - name: POSTGRES_USER
          value: wikijsuser
        - name: POSTGRES_PASSWORD
          value: "54321"
        ports:
        - containerPort: 3306
          name: postgres
        volumeMounts:
        - name: postgres-persistent-storage
          mountPath: /var/lib/postgres
      volumes:
      - name: postgres-persistent-storage
        persistentVolumeClaim:
          claimName: postgres-pv-claim