- name: Reset kubernetes
  become: yes
  shell: kubeadm reset --force

- name: Initialize the cluster
  become: yes
  shell: kubeadm init --pod-network-cidr=10.244.0.0/16 --apiserver-advertise-address=10.132.0.21
  args:
    chdir: $HOME
  register: join_command

- name: Create .kube directory
  file:
    path: .kube
    state: directory
    mode: 0755
    recurse: yes
    owner: utilizador
    group: utilizador

- name: Copy admin.conf to user's kube config
  become: yes
  copy:
    src: /etc/kubernetes/admin.conf
    dest: .kube/config
    remote_src: yes
    owner: utilizador
    group: utilizador

- name: Copy the pod network config
  copy: src=/home/utilizador/ansible/roles/setup_master/files/kube-flannel.yaml dest=/tmp/kube-flannel.yaml mode=0777

- name: Install Pod network
  shell: kubectl apply -f /tmp/kube-flannel.yaml

- name: Copy join command to local file
  local_action: copy content="{{ join_command.stdout_lines[-2][0:-1] }}{{ join_command.stdout_lines[-1] }}" dest="/home/utilizador/ansible/roles/setup_workers/files/join-command"