- name: Reset kubernetes
  shell: kubeadm reset --force

- name: Initialize the cluster
  shell: kubeadm init --pod-network-cidr=10.244.0.0/16
  args:
    chdir: $HOME
  register: join_command

- name: Create .kube directory
  file:
    path: .kube
    state: directory
    mode: 0755
    recurse: yes
    owner: utilizador
    group: utilizador

- name: Copy admin.conf to user's kube config
  copy:
    src: /etc/kubernetes/admin.conf
    dest: .kube/config
    remote_src: yes
    owner: utilizador
    group: utilizador

- name: Install Pod network
  shell: kubectl apply -f https://raw.githubusercontent.com/coreos/flannel/master/Documentation/kube-flannel.yml >> pod_network_setup.txt
  args:
    chdir: $HOME
    creates: pod_network_setup.txt

- name: Copy join command to local file
  local_action: copy content="{{ join_command.stdout_lines[-2][0:-1] }}{{ join_command.stdout_lines[-1] }}" dest="/home/utilizador/ansible/roles/workers/files/join-command"