- name: Configure kubernets apt key
  ansible.builtin.apt_key:
    url: https://packages.cloud.google.com/apt/doc/apt-key.gpg
    state: present

- name: Add Kubernetes' APT repository
  apt_repository:
    repo: deb http://apt.kubernetes.io/ kubernetes-xenial main
    state: present
    filename: 'kubernetes.list'

- name: Install kubernetes
  apt:
    pkg:
    - kubelet=1.22.4-00
    - kubeadm=1.22.4-00
    - kubectl=1.22.4-00
    state: present

- name: disable swap
  shell: |
          swapoff -a
          sed -i '/ swap / s/^\(.*\)$/#\1/g' /etc/fstab

- name: Enable kernel modules
  modprobe:
    name: "{{ item }}"
    state: present
  loop:
    - overlay
    - br_netfilter

- name: Set system configurations for Kubernetes networking
  copy:
    dest: /etc/sysctl.d/99-kubernetes-cri.conf
    content: |
      net.bridge.bridge-nf-call-ip6tables = 1
      net.bridge.bridge-nf-call-iptables = 1
      net.ipv4.ip_forward = 1
  register: networking

- name: Apply new settings
  command: sysctl --system
  when: networking.changed

- name: create Docker config directory
  file: 
    path: /etc/docker 
    state: directory

- name: changing Docker to systemd driver
  copy:
    dest: /etc/docker/daemon.json
    content: |
        {
        "exec-opts": ["native.cgroupdriver=systemd"]
        }

- name: Configure Docker apt key
  ansible.builtin.apt_key:
    url: https://download.docker.com/linux/ubuntu/gpg
    state: present

- name: Install Docker
  apt:
    name: docker.io
    state: latest
