---
- name: playbook for kubernets and docker instalation
  hosts: masters, workers
  remote_user: utilizador
  become: yes
  become_method: sudo
  become_user: root
  gather_facts: yes
  connection: ssh
  roles:
    - role: instalation

  